### ISSUE TITLE
文章图片显示有问题，超出宽度了

### ISSUE THREAD

**Issue by Gracker** [mickeyouyou/yinwang#18]
能限制宽度么？

**Comment by dexterhahaha** [comment]
@mickeyouyou 可以修复一下吗

图片跟着显示范围一起 伸缩 会比较好， 麻烦您修复一下呗

**Comment by Gracker** [comment]
https://github.com/Gracker/hexo-theme-reading
我自己改了一下, 现在宽度没问题了.
不过这个主题缺失的东西比较多, 所以我自己改的一些东西还很乱...
你可以参考一下

**Comment by dexterhahaha** [comment]
感谢

**Comment by mickeyouyou** [comment]
thanks friends
