### ISSUE TITLE
是否可以提供Github默认的代码高亮样式？

### ISSUE THREAD

**Issue by Puriney** [mickeyouyou/yinwang#3]
您自定义的样式是黑色底等。是否可以给一个Github高亮风格的样式？或者您指导一下，我该在哪里进行修改？

``` r
a <- rnorm(100)
```

因为我有其他语言高亮需要，比如R语言等经典程序员不适用的语言。Github高亮风格支持地很好。

O(∩_∩)O谢谢

**Comment by mickeyouyou** [comment]
可以增加这种语言的代码高亮支持，有时间就会更新，感谢关注。

**Comment by mickeyouyou** [comment]
@Puriney  已新增5种代码高亮方式， 欢迎试用~:shipit:
