### ISSUE TITLE
浏览文章时，发现titile没有显示

### ISSUE THREAD

**Issue by cumirror** [mickeyouyou/yinwang#5]
点击文章链接后，只显示文章的内容，文章的titile没有在页面中显示出来。

**Comment by mickeyouyou** [comment]
姿势不对吧 🐙

**Comment by gggin** [comment]
和@cumirror一样
默认的lanscape能显示但是用了theme之后显示不出来了

**Comment by mickeyouyou** [comment]
分别提供个链接我看看

**Comment by gggin** [comment]
gggin.github.io

**Comment by mickeyouyou** [comment]
我发现这其实是一个写法的问题，比如我会在文章开始写一个h2的标题，：

##我是标题2 

以此作为文章的标题。
不过这倒提醒我可以把这个做成一种标准格式。

**Comment by gggin** [comment]
推荐使用landscape的格式

``` markdown
---
title: xxx
---
```

并不是因为我用着方便，而是hexo新手可以无缝对接

**Comment by mickeyouyou** [comment]
可以。

**Comment by gggin** [comment]
哈哈 改好了告诉我

**Comment by NoahDragon** [comment]
@gggin 可以在这条[line](https://github.com/mickeyouyou/yinwang/blob/master/layout/_partial/article.ejs#L7)之上加如下代码:

```
<h2 class="title"><%= post.title%></h2>
```

**Comment by mickeyouyou** [comment]
已更新。
