### ISSUE TITLE
怎么 不让评论显示 的？

### ISSUE THREAD

**Issue by yyyyy** [mickeyouyou/yinwang#6]
配置文件里面没有了?

**Comment by mickeyouyou** [comment]
`_config.yml`就是theme的配置文件

**Comment by NoahDragon** [comment]
https://gist.github.com/NoahDragon/8a9366d4bfcd3fb0e2335d9b75b80d9a
替换theme/yinwang/layout/_partial/article.ejs文件可以删掉评论显示。

或者在每个post的front matter里面加comments: false
![image](https://cloud.githubusercontent.com/assets/5704064/17639946/f581e47c-60c5-11e6-8990-49d2dca3a7a0.png)

**Comment by gggin** [comment]
解决了我的问题 很好

**Comment by mickeyouyou** [comment]
👍
