### ISSUE TITLE
 我的意思是配置文件里面没有设置显示或关闭评论的字段

### ISSUE THREAD

**Issue by yyyyy** [mickeyouyou/yinwang#8]
还有就是分类和标签，也是没有显示的，我在目录中，已经创建了tags文件夹同时也创建了index.md 文件，但标签还是不是显示。
这是你的https://github.com/mickeyouyou/yinwang/blob/master/_config.yml 配置文件中， 我没有找到对应评论设置的地方，求指导。

**Comment by gggin** [comment]
同求

**Comment by NoahDragon** [comment]
#6

**Comment by mickeyouyou** [comment]
https://github.com/mickeyouyou/yinwang/wiki/%E5%A6%82%E4%BD%95%E6%8E%A7%E5%88%B6%E8%AF%84%E8%AE%BA%E6%98%BE%E7%A4%BA%E6%88%96%E8%80%85%E5%85%B3%E9%97%AD%EF%BC%9F
